name: Game Test

on: [ pull_request, push ]

jobs:
  gametest:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'adopt'
          architecture: x64
      - name: Build and run game tests
        run: ./gradlew runGameTest
